# Airbnb Analysis Project Pipeline

This notebook loads the raw Airbnb dataset into SQLite, runs the SQL cleaning pipeline, validates the cleaned data, and exports the final dataset for Tableau.

# Setting up 02_pipeline

In [34]:
import pandas as pd
import numpy as np
import sqlite3
from pathlib import Path

In [35]:
#set project paths

project_root = Path.cwd().parent

raw_data_path = (project_root
                / "data"
                / "raw"
                / "Airbnb_Open_Data.csv"
)

database_path = (project_root
                / "database"
                /"airbnb.db"
)

clean_path = (project_root
              / "sql"
              /"01_clean.sql"
)

analysis_path = (project_root
                 /"sql"
                 /"02_analysis.sql"
)

tableau_path = (project_root
                 /"data"
                 /"tableau"
                 /"listings_clean.csv"
)

# create tableau export folder if it doesn't exist
tableau_path.parent.mkdir(parents=True, exist_ok=True)

# Load the raw CSV

In [36]:
df_raw = pd.read_csv(
    raw_data_path,
    low_memory=False
)

print('Raw Airbnb data loaded successfully!')
print(f'Rows: {df_raw.shape[0]:,}')
print(f'Columns: {df_raw.shape[1]}')

Raw Airbnb data loaded successfully!
Rows: 102,599
Columns: 26

# Standardize column names before SQLite

Since clean SQL column names make the database much easier to deal with, I will just be completing this small preparation in Python

In [37]:
df_raw.columns = (
    df_raw.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^a-z0-9]+", "_", regex=True)
    .str.strip("_")
)

df_raw = df_raw.rename(columns={
    'name': 'listing_name',
    'lat': 'latitude',
    'long': 'longitude'
})

print(df_raw.columns.tolist())

['id', 'listing_name', 'host_id', 'host_identity_verified', 'host_name', 'neighbourhood_group', 'neighbourhood', 'latitude', 'longitude', 'country', 'country_code', 'instant_bookable', 'cancellation_policy', 'room_type', 'construction_year', 'price', 'service_fee', 'minimum_nights', 'number_of_reviews', 'last_review', 'reviews_per_month', 'review_rate_number', 'calculated_host_listings_count', 'availability_365', 'house_rules', 'license']

# Load Raw Data into SQLite

In [38]:
conn = sqlite3.connect(database_path)

df_raw.to_sql(
    'airbnb_raw',
    conn,
    if_exists='replace',
    index=False
)

print('Raw Airbnb loaded into SQLite successfully!')

Raw Airbnb loaded into SQLite successfully!

# Confirm airbnb_raw row count

In [39]:
# confirm raw table row count

raw_count = pd.read_sql_query(
    '''
    SELECT COUNT(*) AS total_rows
    FROM airbnb_raw;
    ''',
    conn
)

display(raw_count)

   total_rows
0      102599

# Preview raw data

In [40]:
sql_preview = pd.read_sql_query(
'''
    SELECT *
    FROM airbnb_raw
    LIMIT 5;
''',
    conn
)

display(sql_preview)

,id,listing_name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,latitude,longitude,country,...,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,None
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,None
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,None,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,None,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",None
3,1002755,None,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,None,None
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",None

# Run SQL Cleaning Pipeline

In [41]:
# run the sql cleaning  script

clean_sql_path = project_root / "sql" / "01_clean.sql"

with open(clean_sql_path, 'r', encoding = 'utf-8') as file:
    clean_sql_script = file.read()

conn.executescript(clean_sql_script)

print('SQL cleaning script executed successfully!')

SQL cleaning script executed successfully!

# Preview airbnb_clean

In [42]:
# preview cleaned sql table

clean_preview = pd.read_sql_query(
'''
    SELECT *
    FROM airbnb_clean
    LIMIT 5;
''',
    conn
)

display(clean_preview)

,id,listing_name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,latitude,longitude,instant_bookable,...,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,0,...,2020.0,966.0,193.0,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,0,...,2007.0,142.0,28.0,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,None,Elise,Manhattan,Harlem,40.80902,-73.94190,1,...,2005.0,620.0,124.0,3.0,0.0,None,0.00,5.0,1.0,352.0
3,1002755,None,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,1,...,2005.0,368.0,74.0,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,0,...,2009.0,204.0,41.0,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0

# Validate Cleaned data

In [43]:
# comparing raw and cleaned data row counts

row_valid = pd.read_sql_query(
'''
    SELECT 
        (SELECT COUNT(*) FROM airbnb_raw) AS raw_count,
        (SELECT COUNT(*) FROM airbnb_clean) AS clean_rows,
        (SELECT COUNT (*) FROM airbnb_raw) - (SELECT COUNT(*) FROM airbnb_clean) AS rows_removed;
''',
    conn
)

display(row_valid)

   raw_count  clean_rows  rows_removed
0     102599      102058           541

# Validate the cleaned values ranges

In [44]:
# validating important cleaned values ranges

range_validation = pd.read_sql_query(
    '''
    SELECT 
        SUM(CASE WHEN price <=0 THEN 1 ELSE 0 END) AS invalid_price,

        SUM(CASE WHEN service_fee < 0 THEN 1 ELSE 0 END) AS invalid_service_fee,

        SUM(
            CASE
                WHEN minimum_nights NOT BETWEEN 1 AND 365 
                THEN 1 ELSE 0 
            END
        ) AS invalid_minimum_nights,

        SUM(
            CASE
                WHEN availability_365 NOT BETWEEN 0 AND 365
                THEN 1 ELSE 0 
            END
        ) AS invalid_availability_365,

        SUM(
            CASE
                WHEN review_rate_number NOT BETWEEN 1 AND 5
                THEN 1 ELSE 0
            END
        ) AS invalid_review_rating,

        SUM(
            CASE
                WHEN number_of_reviews < 0
                THEN 1 ELSE 0 
            END
        ) AS invalid_number_of_reviews
            
    FROM airbnb_clean;
    ''',
    conn
)

display(range_validation)

,invalid_price,invalid_service_fee,invalid_minimum_nights,invalid_availability_365,invalid_review_rating,invalid_number_of_reviews
0,0,0,0,0,0,0

# Export cleaned data for Tableau

In [45]:
# load cleaned sql table into pandas dataframe

df_clean = pd.read_sql_query(
    '''
    SELECT *
    FROM airbnb_clean;
    ''',
    conn
)

print(f'Cleaned dataset loaded {df_clean.shape}')

Cleaned dataset loaded (102058, 22)

In [46]:
# export cleaned data for tableau

df_clean.to_csv(
    tableau_path,
    index=False
)

print('Tableau dataset exported successfully!')
print(tableau_path)

Tableau dataset exported successfully!
c:\Users\jayvy\OneDrive\Documents\jayV388-portfolio\Projects\airbnb_analysis\data\tableau\listings_clean.csv

# Final Pipeline Checks

In [47]:
# confirm tableau export was created

print('Tableau file exists:', tableau_path.exists())
print(f'Exported rows: {df_clean.shape[0]:,}')
print(f'Exported columns: {df_clean.shape[1]}')

Tableau file exists: True
Exported rows: 102,058
Exported columns: 22

In [48]:
# verfiy exported tableau file

tableau_check = pd.read_csv(
    tableau_path,
    low_memory=False
)

print(f'Tableau export shape: {tableau_check.shape}')
display(tableau_check.head())

Tableau export shape: (102058, 22)

,id,listing_name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,latitude,longitude,instant_bookable,...,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,0.0,...,2020.0,966.0,193.0,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,0.0,...,2007.0,142.0,28.0,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,1.0,...,2005.0,620.0,124.0,3.0,0.0,NaN,0.00,5.0,1.0,352.0
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,1.0,...,2005.0,368.0,74.0,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,0.0,...,2009.0,204.0,41.0,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0

In [49]:
# close database connection

conn.close()

print('Database connection closed.')

Database connection closed.